
[functions.analizar-historia]
enabled = true
verify_jwt = true
import_map = "./functions/analizar-historia/deno.json"
entrypoint = "./functions/analizar-historia/index.ts"

[functions.generar-escena]
enabled = true
verify_jwt = true
import_map = "./functions/generar-escena/deno.json"
entrypoint = "./functions/generar-escena/index.ts"

[functions.generar-imagen]
enabled = true
verify_jwt = true
import_map = "./functions/generar-imagen/deno.json"
entrypoint = "./functions/generar-imagen/index.ts"

[functions.crear-estudiante]
enabled = true
verify_jwt = true
import_map = "./functions/crear-estudiante/deno.json"
entrypoint = "./functions/crear-estudiante/index.ts"
